// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU3W--BphbE0SPdN4B7a_U_WFEveSNptk',
    appId: '1:241631399540:web:62971457a6d05320ce0b21',
    messagingSenderId: '241631399540',
    projectId: 'ecommerce-app-f3cdf',
    authDomain: 'ecommerce-app-f3cdf.firebaseapp.com',
    storageBucket: 'ecommerce-app-f3cdf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk4i6Sn2rOpgQXusCxjg4HC5JILiap6-0',
    appId: '1:241631399540:android:3867ccf0242e1a07ce0b21',
    messagingSenderId: '241631399540',
    projectId: 'ecommerce-app-f3cdf',
    storageBucket: 'ecommerce-app-f3cdf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7ObUl2iqb-EJXPyiPzvUSjyWy0Z71M50',
    appId: '1:241631399540:ios:3e5f28dc867bcdbbce0b21',
    messagingSenderId: '241631399540',
    projectId: 'ecommerce-app-f3cdf',
    storageBucket: 'ecommerce-app-f3cdf.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7ObUl2iqb-EJXPyiPzvUSjyWy0Z71M50',
    appId: '1:241631399540:ios:3e5f28dc867bcdbbce0b21',
    messagingSenderId: '241631399540',
    projectId: 'ecommerce-app-f3cdf',
    storageBucket: 'ecommerce-app-f3cdf.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );
}
